package pl.edu.pw.elka.hexancientempires;

/**
 * Displays communicates generated by game.
 * Provides possibility to inform what happen in game
 */
public class Message {
    private String text;
    private long timeLeft;


    /**
     * Display given String for given time as a message on screen
     * @param time in milliseconds
     */
    public void show(String text, long time) {
        this.text = text;
        this.timeLeft = time;
    }

    /**
     * Calculates how much time message will be displayed
     * @param frameTime time of frame in milliseconds
     */
    public void update(long frameTime) {
        timeLeft = Math.max(0, timeLeft - frameTime);
    }

    /**
     * returns if message should be displayed now
     */
    public boolean isDisplaying() {
        return timeLeft > 0;
    }

    public String getText() {
        return text;
    }

    public long getTimeLeft() {
        return timeLeft;
    }
}
